aiakos/openid_provider/urls.py
from django.conf.urls import url

from . import views

app_name = 'openid_provider'

urlpatterns = [
	url(r'^\.well-known/openid-configuration$', views.ConfigurationView.as_view()),

	url(r'^oauth/authorize/$', views.AuthorizationView.as_view(), name='authorization'),
	url(r'^oauth/select-account/$', views.SelectAccountView.as_view(), name='select-account'),
	url(r'^u/(?P<user_id>[^/]+)/oauth/consent/$', views.ConsentView.as_view(), name='consent'),
	url(r'^oauth/token/$', views.TokenView.as_view(), name='token'),
	url(r'^oauth/userinfo/$', views.UserInfoView.as_view(), name='userinfo'),
	url(r'^oauth/jwks/$', views.JWKSView.as_view(), name='jwks'),
	url(r'^oauth/logout/$', views.LogoutView.as_view(), name='logout'),
	url(r'^oauth/account-settings/$', views.AccountSettingsView.as_view(), name='account-settings'),
]

aiakos/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView, TemplateView

from django_extauth import v1 as auth_v1
from rest_framework import routers

from .openid_provider import v1 as oauth_v1

v1 = routers.DefaultRouter()
v1.register(r'clients', oauth_v1.ClientViewSet)
v1.register(r'accounts', auth_v1.AccountViewSet, base_name='account')

urlpatterns = [
	url(r'^v1/', include(v1.urls)),

	url(r'^$', login_required(RedirectView.as_view(url=settings.HOME_URL)), name='home'),

	url(r'^admin/', admin.site.urls),

	url(r'^', include('django_extauth.urls', namespace='extauth')),

	url(r'^', include('aiakos.openid_provider.urls', namespace='openid_provider')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aiakos/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>{{request.get_host|capfirst}} - Aiakos</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="{{bootstrap_theme.url}}" integrity="{{bootstrap_theme.integrity}}" crossorigin="anonymous">

	<style>
	body { padding-top: 70px; }
	.container.narrow { max-width: 500px; }
	.tab-pane { padding-top: 10px; }
	</style>
  </head>
  <body>

	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="{% block navbar-container-class %}container{% endblock %}">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">
					{{request.get_host|capfirst}} - Aiakos
				</a>
			</div>

			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					{% if user.id %}
					<li class="{% if request.resolver_match.url_name == 'settings' %}active{% endif %}"><a href="{% url 'extauth:settings' user.id %}">{% trans "Sign-in settings" %}</a></li>
					{% endif %}
					{% if request.user.is_staff %}
					<li>
						<a href="/admin/">{% trans "Admin" %}</a>
					</li>
					{% endif %}
				</ul>

				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
							{% if user.picture %}
							<img src="{{user.picture}}" style="height: 20px;">
							{% elif user.nickname %}
							{{user.nickname}}
							{% elif user.username %}
							{{user.username}}
							{% elif user.email %}
							{{user.email}}
							{% else %}
							{{user.id}}
							{% endif %}
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu" style="width: 250px;">
							{% for account in request.user.accounts %}
							<li class="{% if account == user %}active{% endif %}">
								<a{% if account.switch %} href="{{account.switch}}"{% endif %}>
									<l><strong>{{account.username}}</strong></l>
									<l>{{account.email}}</l>
								</a>
							</li>
							{% endfor %}
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'extauth:login' %}">{% trans "Add account" %}</a></li>
							<li><a href="{% url 'extauth:logout' %}">{% trans "Sign out" %}</a></li>
						</ul>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>
	<div class="{% block body-container-class %}container{% endblock %}">
		{% for message in messages %}
			<div class="alert alert-info {{ message.tags }}" role="alert">{{ message }}</div>
		{% endfor %}

		{% block content %}
		{% endblock %}
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<script>
	$(document).ready(function(){
		$(".datetime").each(function(){
			$(this).text((new Date($(this).text())).toLocaleString())
		})
	})
	</script>
  </body>
</html>

aiakos/templates/narrow.html
{% extends "base.html" %}

{% block navbar-container-class %}container narrow{% endblock %}
{% block body-container-class %}container narrow{% endblock %}